### ISSUE TITLE
The distance decay is applied twice?

### ISSUE THREAD

**Issue by cocomoff** [Yifang-Qin/DisenPOI#3]
Thank you for making the code public and for your awesome work on the WSDM'23 paper.

After running the code for the public dataset, I have a small concern about the Distance kernel $`w(d_{ij}) := \exp(-d^2_{ij})`$. Here is the input of the Geo GCN:

https://github.com/Yifang-Qin/DisenPOI/blob/04d190e9d059352104d85d8d5b7b3f5f4687f794/LBS.py#L101-L105

Here is the forward implementation of Geo GCN:

https://github.com/Yifang-Qin/DisenPOI/blob/04d190e9d059352104d85d8d5b7b3f5f4687f794/LBS.py#L153-L166

So, I am concerned that the decay (`-dist_vec ** 2`) is applied twice (in L.101 for the first time and L.160 for the second time). I'm sorry if I misunderstood the implementation, and I am happy to discuss the implementation details if possible.

**Comment by Yifang-Qin** [comment]
@cocomoff Thanks for your interest in our work. As you mentioned, there is indeed a problem with the repeated calculation of `dist_weight` in the code. This should be due to mixing different versions of module code when releasing the public version. We appreciate you pointing out the issues in the code, and the LBS.py file has now been updated to fix the issue.

**Comment by cocomoff** [comment]
@Yifang-Qin Thank you for your quick response and great work! :)
